import '../Theme.css';
import '../_color/Theme_color_Gedza.css';
import '../_color/Theme_color_GedzaDark.css';
import '../_control/Theme_control_Gedza.css';
import '../_font/Theme_font_Gedza.css';
import '../_size/Theme_size_Gedza.css';
import '../_space/Theme_space_Gedza.css';
import '../_shadow/Theme_shadow_Gedza.css';
import { ThemePreset } from '../Theme';
export declare const presetGedzaDark: ThemePreset;
